version: v1

#Name of the challenge
name: A brand new avatao challenge

#Difficulty: 10 - 500
difficulty: 100

# Flag if the flag is static
flag: 'flag'

#Enable inputbox to submit flag: true | false
enable_flag_input: false

#Ports: #protocol: ssh | tcp | http #type: raw | embedded
ports:
     8888: {http: raw}

#Required DOCKER capabilities to add
capabilities: []
  
#Skills related to the challenge: ['SQL injection','Web','Linux']
skills: ['skill1','skill2','skill3']

#recommendations:
#    www.docker.com: 'Docker website'
#    www.ubuntu.com: 'Ubuntu webpage'
recommendations:
    <url>: '<name>'

#Original creator of a challenge: ['MITRE Cyber Academy']
owner: ['owner1']
