#Version
version: v1
#Required DOCKER capabilities to add
capabilities: []
#Ports: #protocol: ssh | tcp | http #type: raw | embedded
ports:
    8888: {http: raw}
#Difficulty: 10 - 500
difficulty: 10
#Enable inputbox to submit flag: true | false
enable_flag_input: false
#Flag if flag is static.
#flag: "notstatic"
#Name of the challenge
name: "Buy All The Things - Part 2"
#Skills related to the challenge: ['SQL injection','Web','Linux']
skills: ['Java']
#Recommended readings
recommendations:
    http://www.tutorialspoint.com/java/java_basic_datatypes.htm: 'Java data types'
    http://www.java2s.com/Tutorial/Java/0040__Data-Type/IntegerMAXMINVALUE.htm: 'Java max/min integer value'
#Creator of the challenge
owner: ['your@mail.com']
