#Version
version: v1
#Required DOCKER capabilities to add
capabilities: []
#Ports: #protocol: ssh | tcp | http #type: raw | embedded
ports:
    8888: {http: raw}
#Difficulty: 10 - 500
difficulty: 25
#Enable inputbox to submit flag: true | false
enable_flag_input: true
#Flag if flag is static.
#flag: 'notstatic'
#Name of the challenge
name: 'C Sharp Template'
#Skills related to the challenge: ['SQL injection','Web','Linux']
skills: ['Secure Coding']
recommendations:
    https://en.wikipedia.org/wiki/C_Sharp_(programming_language): 'C#'
#Creator of a challenge
owner: ['gergo.turcsanyi@avatao.com']
