#Version
version: v1
#Required DOCKER capabilities to add
capabilities: []
#Ports: #protocol: ssh | tcp | http #type: raw | embedded
ports:
     8888: {http: raw}
#Difficulty: 10 - 500
difficulty: 100
#Enable inputbox to submit flag: true | false
enable_flag_input: false
#Name of the challenge
name: 'Alert Me 1'
#Skills
skills: ['Web Security','XSS']
#Recommended readings
recommendations:
    https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet/: 'OWASP Cheat Sheet for XSS'
#Creator of the challenge
owner: ['gergo.turcsanyi@avatao.com']

